{
    "type": "bundle",
    "id": "bundle--009b2f53-07d9-46fa-9698-e1fc9a966cee",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--9990ad43-754c-45e0-9482-27e4ae8f663b",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-01-19T00:29:14.788176Z",
            "modified": "2024-01-19T00:29:14.788176Z",
            "name": "CVE-2023-48359",
            "description": "In autotest driver, there is a possible out of bounds write due to improper input validation. This could lead to local denial of service with System execution privileges needed",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2023-48359"
                }
            ]
        }
    ]
}