{
    "type": "bundle",
    "id": "bundle--2405cedc-89ec-4cd2-be8b-13a309a7e6c8",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--118ea153-c877-4ce0-a170-a4a4bb6b5b31",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-05-29T00:30:37.549079Z",
            "modified": "2024-05-29T00:30:37.549079Z",
            "name": "CVE-2024-3657",
            "description": "A flaw was found in 389-ds-base. A specially-crafted LDAP query can potentially cause a failure on the directory server, leading to a denial of service",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-3657"
                }
            ]
        }
    ]
}