{
    "type": "bundle",
    "id": "bundle--f4823caf-e119-4f70-b16c-80bacff624e8",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--80b9d0ea-29ea-4376-a28a-b4af72c1d585",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-02-14T00:37:04.4938Z",
            "modified": "2025-02-14T00:37:04.4938Z",
            "name": "CVE-2024-57782",
            "description": "An issue in Docker-proxy v18.09.0 allows attackers to cause a denial of service.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-57782"
                }
            ]
        }
    ]
}