{
    "type": "bundle",
    "id": "bundle--44f064f0-d9a0-41fc-a24d-abdbb575f461",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--2606fd59-49f5-4eb8-b2d0-e871cabd9621",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-05-22T00:29:11.209719Z",
            "modified": "2024-05-22T00:29:11.209719Z",
            "name": "CVE-2020-36788",
            "description": "In the Linux kernel, the following vulnerability has been resolved:\n\ndrm/nouveau: avoid a use-after-free when BO init fails\n\nnouveau_bo_init() is backed by ttm_bo_init() and ferries its return code\nback to the caller. On failures, ttm_bo_init() invokes the provided\ndestructor which should de-initialize and free the memory.\n\nThus, when nouveau_bo_init() returns an error the gem object has already\nbeen released and the memory freed by nouveau_bo_del_ttm().",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2020-36788"
                }
            ]
        }
    ]
}