{
    "type": "bundle",
    "id": "bundle--20b0b706-f230-489c-8fb3-22ac935e125a",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--5e66a160-0717-439b-87f3-ab19bd88ccad",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-12-13T00:40:41.088852Z",
            "modified": "2024-12-13T00:40:41.088852Z",
            "name": "CVE-2024-54514",
            "description": "The issue was addressed with improved checks. This issue is fixed in watchOS 11.2, tvOS 18.2, macOS Sequoia 15.2, iOS 18.2 and iPadOS 18.2, macOS Ventura 13.7.2, macOS Sonoma 14.7.2. An app may be able to break out of its sandbox.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-54514"
                }
            ]
        }
    ]
}