{
    "type": "bundle",
    "id": "bundle--e12c9b70-b5db-425d-9d56-1b75dfb971c4",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--cb0b53a6-9f5c-43ac-b7f9-4936d4379f56",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-10-02T00:36:02.644006Z",
            "modified": "2024-10-02T00:36:02.644006Z",
            "name": "CVE-2024-8421",
            "description": "This CVE has been rejected.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-8421"
                }
            ]
        }
    ]
}