{
    "type": "bundle",
    "id": "bundle--3ba74fda-c850-4e02-8fe2-288e4a8bad72",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--382dd2ee-34d2-4128-9799-b3b7b4f43dcf",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-09-04T00:19:37.186747Z",
            "modified": "2021-09-04T00:19:37.186747Z",
            "name": "CVE-2021-40490",
            "description": "A race condition was discovered in ext4_write_inline_data_end in fs/ext4/inline.c in the ext4 subsystem in the Linux kernel through 5.13.13.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2021-40490"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}