{
    "type": "bundle",
    "id": "bundle--d2b4b358-7b8c-447e-b0c9-7feac8e7c255",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--f6013e35-09f0-4d9d-9fe7-8bd26c6068c6",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-10-27T00:22:29.234236Z",
            "modified": "2021-10-27T00:22:29.234236Z",
            "name": "CVE-2021-42343",
            "description": "An issue was discovered in Dask (aka python-dask) through 2021.09.1. Single machine Dask clusters started with dask.distributed.LocalCluster or dask.distributed.Client (which defaults to using LocalCluster) would mistakenly configure their respective Dask workers to listen on external interfaces (typically with a randomly selected high port) rather than only on localhost. A Dask cluster created using this method (when running on a machine that has an applicable port exposed) could be used by a sophisticated attacker to achieve remote code execution.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2021-42343"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}