{
    "type": "bundle",
    "id": "bundle--c36c1575-b644-4c10-81b8-77e617445aec",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--8eacabd0-0be2-4fab-9a27-2cb961c12d73",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-05-23T00:29:02.886633Z",
            "modified": "2024-05-23T00:29:02.886633Z",
            "name": "CVE-2024-31904",
            "description": "IBM App Connect Enterprise 11.0.0.1 through 11.0.0.25 and 12.0.1.0 through 12.0.12.0 integration nodes could allow an authenticated user to cause a denial of service due to an uncaught exception.  IBM X-Force ID:  289647.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-31904"
                }
            ]
        }
    ]
}