{
    "type": "bundle",
    "id": "bundle--f630dd0b-eea5-49d3-9ef8-93e0c7c34bfd",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--ac2fe199-ff67-4530-9c6f-ae5bdc006a7a",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-02-28T00:26:36.681927Z",
            "modified": "2024-02-28T00:26:36.681927Z",
            "name": "CVE-2024-25723",
            "description": "ZenML Server in the ZenML machine learning package before 0.46.7 for Python allows remote privilege escalation because the /api/v1/users/{user_name_or_id}/activate REST API endpoint allows access on the basis of a valid username along with a new password in the request body. These are also patched versions: 0.44.4, 0.43.1, and 0.42.2.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-25723"
                }
            ]
        }
    ]
}